#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.cust.prd.url}
    username: ${zero.datasource.cust.prd.username}
    password: ${zero.datasource.cust.prd.password}

#使用柜台 hs-恒生,icbca-工银
trade:
  type: "hs"

# 跳过短信验证码
skip:
  captcha: false
