#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.cust.sit.url}
    username: ${zero.datasource.cust.sit.username}
    password: ${zero.datasource.cust.sit.password}
