package com.minigod.zero.trade.afe.webservice.createaccount;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2024-07-09T10:33:25.789+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://webservice.g3sb.afe.com", name = "CreateAccountPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface CreateAccountPortType {

    @WebMethod(action = "urn:run")
    @Action(input = "urn:run", output = "urn:runResponse")
    @RequestWrapper(localName = "run", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.Run")
    @ResponseWrapper(localName = "runResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.RunResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String run(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );

    @WebMethod(action = "urn:insertOpenAccountMainRecord")
    @Action(input = "urn:insertOpenAccountMainRecord", output = "urn:insertOpenAccountMainRecordResponse")
    @RequestWrapper(localName = "insertOpenAccountMainRecord", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.InsertOpenAccountMainRecord")
    @ResponseWrapper(localName = "insertOpenAccountMainRecordResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.InsertOpenAccountMainRecordResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String insertOpenAccountMainRecord(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );

    @WebMethod(action = "urn:queryEmailAddress")
    @Action(input = "urn:queryEmailAddress", output = "urn:queryEmailAddressResponse")
    @RequestWrapper(localName = "queryEmailAddress", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryEmailAddress")
    @ResponseWrapper(localName = "queryEmailAddressResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryEmailAddressResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryEmailAddress(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );

    @WebMethod(action = "urn:queryMultilingualMessage")
    @Action(input = "urn:queryMultilingualMessage", output = "urn:queryMultilingualMessageResponse")
    @RequestWrapper(localName = "queryMultilingualMessage", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryMultilingualMessage")
    @ResponseWrapper(localName = "queryMultilingualMessageResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryMultilingualMessageResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryMultilingualMessage();

    @WebMethod(action = "urn:queryCommissionScheme")
    @Action(input = "urn:queryCommissionScheme", output = "urn:queryCommissionSchemeResponse")
    @RequestWrapper(localName = "queryCommissionScheme", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryCommissionScheme")
    @ResponseWrapper(localName = "queryCommissionSchemeResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryCommissionSchemeResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryCommissionScheme(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );

    @WebMethod(action = "urn:queryParameters")
    @Action(input = "urn:queryParameters", output = "urn:queryParametersResponse")
    @RequestWrapper(localName = "queryParameters", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryParameters")
    @ResponseWrapper(localName = "queryParametersResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryParametersResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryParameters(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.g3sb.afe.com")
        String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.g3sb.afe.com")
        String args2
    );

    @WebMethod(action = "urn:queryIDNumber")
    @Action(input = "urn:queryIDNumber", output = "urn:queryIDNumberResponse")
    @RequestWrapper(localName = "queryIDNumber", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryIDNumber")
    @ResponseWrapper(localName = "queryIDNumberResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryIDNumberResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryIDNumber(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );

    @WebMethod(action = "urn:queryPhoneNumber")
    @Action(input = "urn:queryPhoneNumber", output = "urn:queryPhoneNumberResponse")
    @RequestWrapper(localName = "queryPhoneNumber", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryPhoneNumber")
    @ResponseWrapper(localName = "queryPhoneNumberResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.QueryPhoneNumberResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public String queryPhoneNumber(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0
    );
}
