#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${minigod.datasource.customer.prd.url}
    username: ${minigod.datasource.customer.prd.username}
    password: ${minigod.datasource.customer.prd.password}
