<p><span style="font-family: 宋体;font-size:16px">日期</span> <span style="font-family: PMingLiU;">:</span> <span style="font-family: PMingLiU;">2021</span><span style="font-family: 宋体;">年</span><span style="font-family: 宋体;">1</span><span style="font-family: 宋体;">月</span><span style="font-family: 宋体;">19</span><span style="font-family: 宋体;">日</span><br /></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">致</span></span> <span style=";font-family:PMingLiU;font-size:16px">:</span> <span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">尊贵的客户</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><strong><span style="font-family: 宋体;font-size: 16px"><span style="font-family:宋体">有关</span></span></strong><strong> </strong><strong><span style="font-family: PMingLiU;font-size: 16px">:</span></strong><strong> </strong><strong><span style="font-family: 宋体;font-size: 16px"><span style="font-family:宋体">公司名称更改</span></span></strong><strong></strong></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">尊贵的客户，根据香港公司注册处于</span></span><span style=";font-family:PMingLiU;font-size:16px">2020</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">年</span></span><span style=";font-family:PMingLiU;font-size:16px">10</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">月</span></span><span style=";font-family:PMingLiU;font-size:16px">8</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">日发出公司更改名称证书后，我司英文名称由「</span></span><span style=";font-family:PMingLiU;font-size:16px">ZSZZ Securities Limited</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">」更改为「</span></span><span style=";font-family:PMingLiU;font-size:16px">zszz Securities Limited</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">」；中文名称由「yff证券有限公司」更改为「智珠证券有限公司」。</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p style="background:rgb(255,255,255)"><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">敬请客户注意向我司入金时需以新名称</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">「</span></span><span style=";font-family:PMingLiU;font-size:16px">zszz Securities Limited</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">」或「智珠证券有限公司」抬头</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">存入资金</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">。</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">更改</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">我司</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">名称将不会影响</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">各尊贵客户的</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">权利，</span></span><span style=";font-family:宋体;font-size:16px;background:rgb(255,255,255)"><span style="font-family:宋体">客户所有资产依旧享有法定保障</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">。所有印有</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">我司</span></span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">前名称之系统、文件、结单将继续有效。</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">我司将继往开来，坚持为各尊贵的客户提供优质的证券买卖服务。</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:13px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">如有任何疑问，欢迎致电我司客服热线</span></span><span style=";font-family:PMingLiU;font-size:16px">(</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">电话</span></span><span style=";font-family:PMingLiU;font-size:16px">400-***)</span><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">或电邮至</span></span><span style=";font-family:PMingLiU;font-size:16px">cs@zszz.com.</span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">此致</span></span></p>
<p><span style=";font-family:PMingLiU;font-size:16px">&nbsp;</span></p>
<p><span style=";font-family:宋体;font-size:16px"><span style="font-family:宋体">智珠证券有限公司</span></span></p>
<p><span style=";font-family:'Times New Roman';font-size:14px">&nbsp;</span></p>
<p><br /></p>
