#spring配置
spring:
  redis:
    ##redis 单机环境配置
    #host: 127.0.0.1
    #port: 6379
    password: ZxcvyG789GF
    database: 0
    ssl: false
    timeout: 10000ms
    ##redis 集群环境配置
    cluster:
      nodes: 10.9.68.177:7001, 10.9.68.177:7002, 10.9.68.178:7003, 10.9.68.178:7004, 10.9.68.179:7005, 10.9.68.179:7006
      commandTimeout: 5000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #driver-class-name: dm.jdbc.driver.DmDriver
    druid:
      # MySql、PostgreSQL、SqlServer、DaMeng校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual

#项目模块集中配置
zero:
  #分布式锁配置
  lock:
    enabled: true
    #address: redis://10.9.68.177:7001
    password: ZxcvyG789GF
    database: 1
    #集群模式
    mode: cluster
    nodeAddress: redis://10.9.68.177:7001, redis://10.9.68.177:7002, redis://10.9.68.178:7003, redis://10.9.68.178:7004, redis://10.9.68.179:7005, redis://10.9.68.179:7006
  #多团队协作服务配置
  loadbalancer:
    #开启配置
    enabled: true
    #负载均衡优先调用的ip段
    prior-ip-pattern:
      - 10.9.28.*
      - 127.0.0.1
  #通用开发生产环境数据库地址(特殊情况可在对应的子工程里配置覆盖)
  datasource:
    dev:
      # MySql
      url: jdbc:mysql://10.9.68.213:3306/zero_cloud?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
      username: sunline
      password: Sunline!@#123
    job:
      dev:
        # MySql
        url: jdbc:mysql://10.9.68.213:3306/zero_job?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
        username: sunline
        password: Sunline!@#123
