package com.minigod.zero.trade.afe.webservice.generalservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2024-10-24T15:18:55.680+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://webservice.g3sb.afe.com", name = "GeneralServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface GeneralServicePortType {

    @WebMethod(action = "urn:messageTransfer")
    @Action(input = "urn:messageTransfer", output = "urn:messageTransferResponse")
    @RequestWrapper(localName = "messageTransfer", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.MessageTransfer")
    @ResponseWrapper(localName = "messageTransferResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.afe.g3sb.webservice.MessageTransferResponse")
    @WebResult(name = "return", targetNamespace = "http://webservice.g3sb.afe.com")
    public java.lang.String messageTransfer(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        java.lang.String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.g3sb.afe.com")
        java.lang.String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.g3sb.afe.com")
        java.lang.String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.g3sb.afe.com")
        java.lang.String args3
    );
}
