#服务器端口
server:
  port: 8100

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.dev.url}
    username: ${zero.datasource.dev.username}
    password: ${zero.datasource.dev.password}

esop:
  loginUrl: "http://esop-admin.reotest.com/login"
