knife4j:
  cloud:
    routes:
      - name: 授权模块
        uri: https://xxxxx #网关地址
        location: /zero-auth/v2/api-docs
      - name: 系统模块
        uri: https://xxxxxxxx
        location: /zero-system/v2/api-docs
      - name: 用户模块
        uri: https://zero-sit.xxxx.cn
        location: /zero-user/v2/api-docs
      - name: 客户模块
        uri: https://zero-sit.xxxx.cn
        location: /zero-cust/v2/api-docs
      - name: 行情管理模块
        uri: https://zero-sit.xxxx.cn
        location: /mktmgr-server/v2/api-docs
      - name: 资源/短信模块
        uri: https://zero-sit.xxxx.cn
        location: /zero-resource/v2/api-docs
      - name: 行情核心模块
        uri: https://mkt-sit.xxxx.cn
        location: /mktquot-core/v2/api-docs
      - name: 资讯核心模块
        uri: https://mkt-sit.xxxxx.cn
        location: /mktinfo-core/v2/api-docs


