#Docker镜像可以选择以下三种，前两种已经内置字体，第三种为原生的openjdk8-openj9镜像
#1.FROM zero-cloud/alpine-java:8_server-jre_cn_unlimited
#2.FROM zero-cloud/alpine-java:openjdk8-openj9_cn_slim
#3.FROM adoptopenjdk/openjdk8-openj9:jdk8u262-b10_openj9-0.21.0-alpine-slim
#第3点的tag可以到该地址查询：https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9/tags?page=1&ordering=last_updated&name=alpine-slim
#版本介绍一览：https://hub.docker.com/r/adoptopenjdk/openjdk8-openj9
FROM baseimages/openjdk:11-jdk-slim-fontconfig

LABEL MAINTAINER=tech-operations@yff.com

RUN mkdir -p /zero/cloud/zero-auth-biz

#增加字体，解决验证码没有字体报空指针问题
RUN set -xe \
    apt-get update && apt-get install -y fontconfig
    #&& apk --no-cache add ttf-dejavu fontconfig


WORKDIR /zero/cloud/zero-auth-biz
ENV SW_AGENT_NAME=zero-auth-biz
ENV SW_AGENT_COLLECTOR_BACKEND_SERVICES=skywalking-oap.skywalking:11800
COPY apache-skywalking-java-agent-9.3.0.tgz .
ENV SW_AGENT_SPAN_LIMIT=2000
RUN tar xf apache-skywalking-java-agent-9.3.0.tgz
EXPOSE 8000

ADD ./target/zero-auth-biz.jar ./app.jar

ENTRYPOINT ["java", "-javaagent:skywalking-agent/skywalking-agent.jar", "-Dfile.encoding=UTF-8", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
#ENTRYPOINT ["java", "-Dfile.encoding=UTF-8", "-Djava.security.egd=file:/dev/./urandom", "-jar", "app.jar"]
