#数据源配置
spring:
  datasource:
    url: ${minigod.datasource.customer.sit.url}
    username: ${minigod.datasource.customer.sit.username}
    password: ${minigod.datasource.customer.sit.password}

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888
