#服务器端口
server:
  port: 8107

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.dev.url}
    username: ${zero.datasource.dev.username}
    password: ${zero.datasource.dev.password}

#默认对象存储配置
oss:
  enabled: true
  name: qiniu
  tenant-mode: false
  endpoint: https://xxxxxx.xxx.cn
  access-key: U8VGSrOjjPpoPFEG-qHUJrywNL743V2PsrMjW6WM
  secret-key: ZcWIywOvp1NaaUNMU0o3ml8OTC-kk8TG_5e_T0kN
  bucket-name: xxxx


