
-- 这个SQL脚本文件不需要再执行，最后执行v3.0.0目录下的【zero-biz-bpmn-01-sys_item_config-heyong.sql】即可。
ALTER TABLE `zero_bpmn`.`sys_item_config` MODIFY COLUMN `item_label` varchar(800) CHARACTER SET utf8 COLLATE utf8_bin NULL DEFAULT NULL COMMENT '配置项文本';




INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001111, '000000', 'confirmation_treatment_professional_investor', '本人/我們並茲聲明本人/我們同意被視為該相關投資產品種類的專業投資者及本人/我們已閱讀及明白成為專業投資者的風險及結果。', 'A', 1, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001112, '000000', 'confirmation_treatment_professional_investor', '本人/我們瞭解在相關投資產品及市場上進行交易所涉及的風險。', 'B', 2, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001113, '000000', 'confirmation_treatment_professional_investor', '本人/我們茲聲明確認對有關產品及市場擁有足夠認識，投資經驗與及承擔險之能力，本人/我們有能力且已詳細審閱有關 投資產品包含未經香港證監會認可之投資產品 (以下簡稱「非認可投資產品」) 的銷售文件，包括相關之風險揭露與銷售限制，並可充分瞭解非認可投資產品的投資目標與投資策略，及投資策略可能隱含之風險。', 'C', 3, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001114, '000000', 'confirmation_treatment_professional_investor', '本人/我們確實瞭解非認可投資產品贖回款項所需要的時間可能比傳統型產品長得多，故已於進行投資非認可投資產品之前 仔細考慮本身資金周轉需要。', 'D', 4, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001115, '000000', 'confirmation_treatment_professional_investor', '本人/我們知道並同意獅瀚環球金融不需要為本人/我們提供根據證券及期貨 (成交單據、戶口結單及收據) 規則發出的成交單據、戶口結單及收據。', 'E', 5, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001116, '000000', 'confirmation_treatment_professional_investor', '本人/我們同意若上述的任何聲明或資料有任何更改，本人/我們將會立即通知獅瀚環球金融及更新相關資料並提供獅瀚環球金融合理要求的文件。', 'F', 6, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001117, '000000', 'confirmation_treatment_professional_investor', '本人/我們瞭解本人/我們可以隨時撤回同意被視為專業投資者之聲明，客戶需在 14 個工作天前書面提出，在獅瀚環球金融發出撤回確認書後的一個工作天後生效。若本人/我們撤回生效後，獅瀚環球金融不應再視本人/我們為專業投資者。同時，獅瀚環球金融可每年進行一次確認，從而確保本人/我們繼續符合《證券及期貨(專業投資者)規則》所界定的有關規定。', 'G', 7, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001118, '000000', 'confirmation_treatment_professional_investor', '本人確認獅瀚環球金融提供英文和中文客戶協議包括第 22 點的風險披露聲明，我進一 步確認獅瀚環球金融已經邀請我閱讀風險披露聲明，提出問題及徵求獨立的意見（如我有此意願）。', 'H', 8, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000001119, '000000', 'confirmation_treatment_professional_investor', '本人/我們確實了解以上聲明之內容，並承諾本聲明書之內容均為真實及完整。', 'I', 9, 'zh-hant', NOW(), NOW(), NULL, NULL, 0);







INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002221, '000000', 'confirmation_treatment_professional_investor', '本人/我们并兹声明本人/我们同意被视为该相关投资产品种类的专业投资者及本人/我们已阅读及明白成为专业投资者的风险及结果。', 'A', 1, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002222, '000000', 'confirmation_treatment_professional_investor', '本人/我们瞭解在相关投资产品及市场上进行交易所涉及的风险。', 'B', 2, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002223, '000000', 'confirmation_treatment_professional_investor', '本人/我们兹声明确认对有关产品及市场拥有足够认识，投资经验与及承担险之能力，本人/我们有能力且已详细审阅有关 投资产品包含未经香港证监会认可之投资产品 (以下简称“非认可投资产品”) 的销售文件，包括相关之风险揭露与销售限制，并可充分瞭解非认可投资产品的投资目标与投资策略，及投资策略可能隐含之风险。', 'C', 3, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002224, '000000', 'confirmation_treatment_professional_investor', '本人/我们确实瞭解非认可投资产品赎回款项所需要的时间可能比传统型产品长得多，故已于进行投资非认可投资产品之前 仔细考虑本身资金周转需要。', 'D', 4, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002225, '000000', 'confirmation_treatment_professional_investor', '本人/我们知道并同意狮瀚环球金融不需要为本人/我们提供根据证券及期货 (成交单据、户口结单及收据) 规则发出的成交单据、户口结单及收据。', 'E', 5, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002226, '000000', 'confirmation_treatment_professional_investor', '本人/我们同意若上述的任何声明或资料有任何更改，本人/我们将会立即通知狮瀚环球金融及更新相关资料并提供狮瀚环球金融合理要求的文件。', 'F', 6, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002227, '000000', 'confirmation_treatment_professional_investor', '本人/我们瞭解本人/我们可以随时撤回同意被视为专业投资者之声明，客户需在 14 个工作天前书面提出，在狮瀚环球金融发出撤回确认书后的一个工作天后生效。若本人/我们撤回生效后，狮瀚环球金融不应再视本人/我们为专业投资者。同时，狮瀚环球金融可每年进行一次确认，从而确保本人/我们继续符合《证券及期货(专业投资者)规则》所界定的有关规定。', 'G', 7, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002228, '000000', 'confirmation_treatment_professional_investor', '本人确认狮瀚环球金融提供英文和中文客户协议包括第 22 点的风险披露声明，我进一 步确认狮瀚环球金融已经邀请我阅读风险披露声明，提出问题及徵求独立的意见（如我有此意愿）。', 'H', 8, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000002229, '000000', 'confirmation_treatment_professional_investor', '本人/我们确实了解以上声明之内容，并承诺本声明书之内容均为真实及完整。', 'I', 9, 'zh-hans', NOW(), NOW(), NULL, NULL, 0);



INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003331, '000000', 'confirmation_treatment_professional_investor', 'I / We hereby declare that I / we agree to be treated as Professional Investor of that type of relevant product and have read and understood the risk and consequence of being treated as professional investor(s).', 'A', 1, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003332, '000000', 'confirmation_treatment_professional_investor', 'I am / We are aware of the risks involved in trading in the relevant investment products and markets.', 'B', 2, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003333, '000000', 'confirmation_treatment_professional_investor', 'I / We hereby confirm that I / we have sufficient knowledge and expertise in relevant products and markets and able to bear the risk involved, I / we have the ability to study and have already studied on the relevant products, including the documents of the investment products which have not been approved by Securities and Futures Commission, namely “unauthorized products”, and which includes relative risks disclosure and trading limitation, and can fully understand the investment targets,investment tactics and potential risks.', 'C', 3, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003334, '000000', 'confirmation_treatment_professional_investor', 'I/We confirm that I/we understand the period for redeeming the principal of unauthorized investment products will be much longer than the traditional products, so I/We must consider carefully about my/our cashflow before investing on these unauthorized investment products.', 'D', 4, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003335, '000000', 'confirmation_treatment_professional_investor', 'I/We acknowledge and agree that Lion Global Financial is not required to provide us with contract notes, statements of accounts or receipt in accordance to the Securities and Futures (Contract Notes, Statements of Accounts and Receipts) Rules.', 'E', 5, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003336, '000000', 'confirmation_treatment_professional_investor', 'I/We agree that if there is any change of status or circumstance which may render any declarations or information indicated above, I/we will inform Lion Global Financial immediately and will update such information, complete such forms or provide such documents as Lion Global Financial may reasonably require.', 'F', 6, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003337, '000000', 'confirmation_treatment_professional_investor', 'I / We understand that we can withdraw this declaration by providing a written request to Lion Global Financial at least 14 business days beforehand, and it will be effective one business day after Lion Global Financial issue a withdrawal confirmation. Lion Global Financial will not treat me / us as Professional Investor after the withdrawal request is effective. I / we also agree that PSHK will carry out a confirmation exercise annually to ensure that I / we continue to fulfil the requisite asset or portfolio requirements in Securities and Futures (Professional Investor) Rule.', 'G', 7, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003338, '000000', 'confirmation_treatment_professional_investor', 'I/We acknowledge that the Client Agreement including the Risk Disclosure Statements in Point 22 attached were provided in a language English and Chinese. I /We further acknowledge that I /We was invited to read the risk disclosure statements, ask questions and take independent advice, if I wished.', 'H', 8, 'en', NOW(), NOW(), NULL, NULL, 0);
INSERT INTO `zero_bpmn`.`sys_item_config` (`id`, `tenant_id`, `item_type`, `item_label`, `item_value`, `sort`, `lang`, `create_time`, `update_time`, `update_user`, `create_user`, `is_deleted`) VALUES (1902588644000003339, '000000', 'confirmation_treatment_professional_investor', 'I / We confirm that the contents of this declaration and agree that the information in this declaration is true and complete.', 'I', 9, 'en', NOW(), NOW(), NULL, NULL, 0);
