-- PI申请提交
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3401, 'zero-biz-bpmn', 'pi_application_submit_failed_param_notice', 'zh-CN', '提交专业投资者PI认证申请失败,参数为空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3402, 'zero-biz-bpmn', 'pi_application_submit_failed_param_notice', 'zh-HK', '提交專業投資者PI認證申請失敗,參數為空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3403, 'zero-biz-bpmn', 'pi_application_submit_failed_param_notice', 'en-US', 'Failed to submit professional investor PI certification application, parameter is empty!', NULL, NULL, NULL, NULL, 0, 0);



INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3404, 'zero-biz-bpmn', 'pi_application_submit_failed_treatment_notice', 'zh-CN', '提交专业投资者PI认证申请失败,专业投资者之待遇为空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3405, 'zero-biz-bpmn', 'pi_application_submit_failed_treatment_notice', 'zh-HK', '提交專業投資者PI認證申請失敗,專業投資者之待遇為空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3406, 'zero-biz-bpmn', 'pi_application_submit_failed_treatment_notice', 'en-US', 'Failed to submit PI certification application for professional investors, treatment for professional investors is empty!', NULL, NULL, NULL, NULL, 0, 0);



INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3407, 'zero-biz-bpmn', 'pi_application_submit_failed_declaration_notice', 'zh-CN', '专业投资者申请操作,专业投资者之被视为专业投资者身份的确认书声明(勾选项)为空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3408, 'zero-biz-bpmn', 'pi_application_submit_failed_declaration_notice', 'zh-HK', '專業投資者申請操作,專業投資者之被視為專業投資者身份的確認書聲明(勾選項)為空!', NULL, NULL, NULL, NULL, 0, 0);
INSERT INTO `zero_cloud`.`zero_i18n_config` (`id`, `sys_model`, `config_key`, `language_type`, `content`, `create_user`, `create_time`, `update_user`, `update_time`, `status`, `is_deleted`) VALUES (3409, 'zero-biz-bpmn', 'pi_application_submit_failed_declaration_notice', 'en-US', 'Professional investor application operation, the confirmation statement of professional investor\'s identity as a professional investor (check box) is empty!', NULL, NULL, NULL, NULL, 0, 0);
