#服务器端口
server:
  port: 8000

#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/account_prd_1029?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: root
#    password: 123456
#  redis:
#    ##redis 单机环境配置
#    host: 203.86.123.85
#    port: 35769
#    password: 'UZhF01phE#2342fp'
#    database: 0
#    ssl: false
#    timeout: 50000


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
