#服务器端口
server:
  port: 8000
#开启sql日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#数据源配置
spring:
  datasource:
    url: ${zero.datasource.flow.sit.url}
    username: ${zero.datasource.flow.sit.username}
    password: ${zero.datasource.flow.sit.password}
