#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.flow.prd.url}
    username: ${zero.datasource.flow.prd.username}
    password: ${zero.datasource.flow.prd.password}
