#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.bpmn.dev.url}
    username: ${zero.datasource.bpmn.dev.username}
    password: ${zero.datasource.bpmn.dev.password}

