#数据源配置
spring:
  datasource:
    url: ${zero.datasource.dev.url}
    username: ${zero.datasource.dev.username}
    password: ${zero.datasource.dev.password}
  mvc:
    async:
      requestTimeout: 20000

#第三方登陆
social:
  enabled: true
  domain: http://127.0.0.1:1888

