#服务器端口
server:
  port: 8000

#数据源配置
spring:
  datasource:
    url: ${zero.datasource.cust.dev.url}
    username: ${zero.datasource.cust.dev.username}
    password: ${zero.datasource.cust.dev.password}
