CREATE TABLE `ta_t_holding_history` (
                                        `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT '记录标志',
                                        `subAccountId` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '账号',
                                        `fundCode` varchar(32) COLLATE utf8mb4_general_ci NOT NULL COMMENT '产品/现金id',
                                        `holdingType` int unsigned NOT NULL DEFAULT '1' COMMENT '持仓类型，1：fund；2：cash；3：icp；64 活利得  65 债券易',
                                        `totalQuantity` decimal(19,8) DEFAULT '0.00000000',
                                        `availableQuantity` decimal(19,8) DEFAULT '0.00000000',
                                        `frozenQuantity` decimal(19,8) DEFAULT '0.00000000',
                                        `transitedQuantity` decimal(19,8) DEFAULT '0.00000000',
                                        `withdrawQuantity` decimal(19,8) DEFAULT '0.00000000',
                                        `averageCost` decimal(27,16) DEFAULT '0.0000000000000000',
                                        `dilutedCost` decimal(27,16) DEFAULT '0.0000000000000000',
                                        `currency` varchar(10) COLLATE utf8mb4_general_ci DEFAULT NULL COMMENT '货币类型',
                                        `accumulatedBuyAmount` decimal(19,8) DEFAULT '0.00000000',
                                        `accumulatedCashDividends` decimal(19,8) DEFAULT '0.00000000',
                                        `realizedGainLoss` decimal(19,8) DEFAULT '0.00000000',
                                        `capitalGainLoss` decimal(19,8) DEFAULT '0.00000000' COMMENT '债券易卖出资本利得',
                                        `totalGainLoss` decimal(19,8) DEFAULT '0.00000000' COMMENT '总盈亏',
                                        `totalFee` decimal(19,8) DEFAULT '0.00000000',
                                        `expectedRate` decimal(10,4) DEFAULT NULL COMMENT '预期年化收益率',
                                        `flowId` int NOT NULL DEFAULT '0' COMMENT '对应flow记录的主键，如果主键有多个字段，需要扩充',
                                        `transactionTime` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
                                        `createTime` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
                                        `updateTime` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '修改时间',
                                        PRIMARY KEY (`id`),
                                        UNIQUE KEY `idx_subaccountid_fundcode_flowid` (`fundCode`,`subAccountId`,`flowId`)
) ENGINE=InnoDB AUTO_INCREMENT=4369 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=COMPACT;
