
package com.minigod.too;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GeneralServicePortType", targetNamespace = "http://webservice.g3sb.afe.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GeneralServicePortType {


    /**
     * 
     * @param args1
     * @param args2
     * @param args3
     * @param args0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:messageTransfer")
    @WebResult(targetNamespace = "http://webservice.g3sb.afe.com")
    @RequestWrapper(localName = "messageTransfer", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.minigod.too.MessageTransfer")
    @ResponseWrapper(localName = "messageTransferResponse", targetNamespace = "http://webservice.g3sb.afe.com", className = "com.minigod.too.MessageTransferResponse")
    public String messageTransfer(
        @WebParam(name = "args0", targetNamespace = "http://webservice.g3sb.afe.com")
        String args0,
        @WebParam(name = "args1", targetNamespace = "http://webservice.g3sb.afe.com")
        String args1,
        @WebParam(name = "args2", targetNamespace = "http://webservice.g3sb.afe.com")
        String args2,
        @WebParam(name = "args3", targetNamespace = "http://webservice.g3sb.afe.com")
        String args3);

}
