server:
  port: 8000
  servlet:
    context-path: /xxljob-admin

spring:
  cloud:
    nacos:
      discovery:
        metadata:
          management:
            context-path: /actuator
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.######
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    host: smtp.qq.com
    username: tech-operations@qq.com
    password: syizkiatfgtadgcj
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true
    from: tech-operations@qq.com
  mvc:
    servlet:
      load-on-startup: 0
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

management:
  health:
    mail:
      enabled: false
  server:
    base-path: /actuator
mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml

xxl:
  job:
    accessToken: default_token
    i18n: zh_CN
    logretentiondays: 30
    triggerpool:
      fast:
        max: 200
      slow:
        max: 100

